#!/bin/bash -ex
cd `dirname $0`

#echo "أَمْجَد كَانَ لَهُ قَصْر إِلَى الْمَمْلَكَة الْمَغْرِبِيَّة" | \
ruby -e "require 'unicode_utils'; puts UnicodeUtils.nfc(readline)" | \
  python ../../buckwalter2unicode/buckwalter2unicode.py -r -i /dev/stdin -o /dev/stdout
